name: Draw ZMK keymaps
on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/keymap_draser.yml"
      - "keymap_drawer.config.yaml"
      - "config/**"

jobs:
  draw:
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      contents: write
    steps:
      - name: Draw keymap
        uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
        with:
          commit_message: "[Draw] ${{ github.event.head_commit.message }}"
          amend_commit: false
          install_branch: "main"
          keymap_patterns: "config/*.keymap"
          json_path: "config"
          config_path: "keymap_drawer.config.yaml" # config file, ignored if not exists
          output_folder: "keymap-drawer"
          destination: "both"
          parse_args: ""  # map of extra args to pass to `keymap parse`, e.g. "corne:'-l Def Lwr Rse' cradio:''"
          draw_args: ""   # map of extra args to pass to `keymap draw`, e.g. "corne:'-k corne_rotated' cradio:'-k paroxysm'"
      - name: Upload svg
        uses: aws-actions/configure-aws-credentials@v1
        with:
          cloud-name: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          api-key: ${{ secrets.CLOUDINARY_API_KEY }}
          api-secret: ${{ secrets.CLOUDINARY_API_SECRET }}
          image: "./keymap-drawer/oddball.svg"